### ISSUE TITLE
No page numbers before 2005

### ISSUE THREAD

**Issue by danielgildea** [acl-org/acl-anthology#173]
Page numbers and other bib info are present in the bib entries in the old anthology, but seem to have gotten dropped.

https://www.dropbox.com/s/4i3rqsy12x637ho/anthology_bib.tgz?dl=0

**Comment by davidweichiang** [comment]
There are several other fields missing as well. And an entire workshop (W15-57, Workshop on Deep Machine Translation).

I've written a merge script that can restore all these fields from the .bib, but maybe it should wait until `static-rewrite` is merged and the dust settles.

**Comment by danielgildea** [comment]
Also many CL journal articles have the wrong author order:
http://www.aclweb.org/anthology/J01-2003
(seems to be an issue of reading down vs. across the author list on the title page!)

**Comment by davidweichiang** [comment]
The missing fields (and workshop W15-57) have been added in https://github.com/acl-org/acl-anthology/tree/merge-fields .

**Comment by mjpost** [comment]
@davidweichiang, I just merged static-rewrite into this branch and created a PR (#188). Can you check that this looks okay?

**Comment by davidweichiang** [comment]
The journal authors lists are still not fixed, unless Dan fixed them.

**Comment by davidweichiang** [comment]
@danielgildea are there still author lists to correct?

**Comment by danielgildea** [comment]
All author lists are fixed.  CL is still missing page numbers for 2002-2013,
which did not have bibtex in the old anthology.
