### ISSUE TITLE
Metadata correction for 2023.eamt-1.38

### ISSUE THREAD

**Issue by FadiGhawanmeh** [acl-org/acl-anthology#5752]
### JSON data block

```json
{
  "anthology_id": "2023.eamt-1.38",
  "abstract": "This article presents a system to generate Arab music improvisation using machine translation (MT). To reach this goal, we developed a MT model to translate a vocal improvisation into an automatic instrumental oud (Arab lute) response. Given the melodic and non-metric musical form, it was necessary to develop efficient textual representations in order for classical MT models to be as successful as in common NLP applications. We experimented with Statistical and Neural MT to train our parallel corpus (Vocal → Instrument) of 6991 sentences. The best model was then used to generate improvisation by iteratively translating the translations of the most common patterns of each maqam (n-grams), producing elaborated variations conditioned to listener feedback. We constructed a dataset of 717 instrumental improvisations to extract their n-grams. Objective evaluation of MT was conducted at two levels: a sentence-level evaluation using the BLEU metric, and a higher level evaluation using musically informed metrics. Objective measures were consistent with one another. Subjective evaluations by experts from the maqam music tradition were promising, and a useful reference for understanding objective results.",
  "authors": [
    {
      "first": "Fadi",
      "last": "Al-Ghawanmeh",
      "id": "fadi-al-ghawanmeh"
    },
    {
      "first": "Alexander Refsum",
      "last": "Jensenius",
      "id": "alexander-jensenius"
    },
    {
      "first": "Kamel",
      "last": "Smaili",
      "id": "kamel-smaili"
    }
  ],
  "authors_old": "Fadi  Al-Ghawanmeh | Alexander  Jensenius | Kamel  Smaili",
  "authors_new": "Fadi  Al-Ghawanmeh | Alexander Refsum  Jensenius | Kamel  Smaili"
}
```

**Comment by nschneid** [comment]
@FadiGhawanmeh in the PDF if has "Refsum" not "R.". Should it be part of the first name or last name?

**Comment by FadiGhawanmeh** [comment]
Hi, Thanks for the follow up. It is the middle initial, so you may consider it part of the first name. Thanks


 

    On Wednesday, August 13, 2025 at 10:03:44 AM EDT, Nathan Schneider ***@***.***> wrote:  
 
 nschneid left a comment (acl-org/acl-anthology#5752)
@FadiGhawanmeh in the PDF if has "Refsum" not "R.". Should it be part of the first name or last name?

**Comment by nschneid** [comment]
Fixed.

**Comment by FadiGhawanmeh** [comment]
Hi, I still see the abstract in this page (How can machine translation help generate Arab melodic improvisation? - ACL Anthology) different than the one inside the PDF document. The one in the page has repeated text segments in a confusing way. I wanted to fix the problem by simply copying the abstract from the PDF and pasting it in this page. can you help?
ThanksFadi


 

    On Tuesday, August 19, 2025 at 09:09:15 AM EDT, Nathan Schneider ***@***.***> wrote:  
 
 nschneid left a comment (acl-org/acl-anthology#5752)
Fixed.
